import google.generativeai as genai
import os
from dotenv import load_dotenv
import logging
 
# Load env vars
load_dotenv()
 
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
genai.configure(api_key=GEMINI_API_KEY)
 
# Use Gemini model
model = genai.GenerativeModel('models/gemini-1.5-flash-latest')
 
# Configure logging
logging.basicConfig(filename='chatbot_debug.log', level=logging.INFO, 
                    format='%(asctime)s %(levelname)s %(message)s')
 
def generate_sql(user_query):
    """Generate SQL query from natural language"""
    logging.info(f"Generating SQL for user query: {user_query}")
    try:
        sql_prompt = f"""
        You are an Oracle SQL generator. Convert this question to a valid Oracle SQL query (no explanation and no updation/deletion/insertion):Schema of database is there-
        Tables and columns-
        TXN_SITE_INVOICE_DETAILS(COUNTRY_ID, BILL_MONTH, SEARCH_MONTH, INVOICE_START_DATE, INVOICE_END_DATE, INVOICE_ID, SITERRA_SITE_ID, SITE_NAME, SITE_TYPE, INTERNAL_SLA_CLASS, LEGACY_ID, FINANCE_ID, OWNERSHIP_TYPE, GRID_STATUS, SHARABILITY, REGION_NAME, PROVINCE, PORTFOLIO, SITE_STATUS, SITE_SOURCE, GRID_CONNECTION_DATE, ANCHOR_TENANT, MULTI_TENANCY_STATUS, TENANTS_TOTAL, ON_AIR_DATE, CONSOL_DATE, DECOM_DATE, OFFLINE_DATE, RELO_DATE, TENANT_LOAD_POSITION1, TENANT_LOAD_POSITION2, TENANT_LOAD_POSITION3, TENANT_LOAD_POSITION4, SITERRA_TENANCY_ID, SAP_CUSTOMER_NO, CUSTOMER_NAME, CUSTOMER_SITE_ID, CUSTOMER_NAME_KNOWN_AS, SITE_CLASS, MOVE_IN_DATE, MOVE_OUT_DATE, SLA_START_DATE, RFI_DATE, SAF_DATE, ORIGINAL_EXPIRATION_DATE, CLASSIFICATION_OVER_RIDE, CANCEL_DATE, REPORTING_DATE, LEASESTART_DATE, RENT_FREE_PERIOD, RENT_START_DATE, SLA_CLASS, LEASESTATUS, TENANCY_TYPE, OUTDOOR, MASTER_CLASSIFICATION, TENANCY_CLASSIFICATION_SITE_BILLING_TYPE, ST_ID, AIRTEL_SPECIAL_OFFER, TRANSACTION_STATUS, FX_RATE, CUMULATIVE_ESCALATION, AMENDMENT_PERC_TO_APPLY, ON_AIR_PRORATED_FACTOR, LEASE_TYPE_DIESEL, LEASE_TYPE_NONENERGY, LEASE_TYPE_ELECTRICITY, LEASE_TYPE_MAINTAINED, LEASE_TYPE_MANAGED, LEASE_COMP_ELECTRICITY, LEASE_COMP_DIESEL, LEASE_COMP_NONENERGY, LEASE_COMP_MANAGED, LEASE_COMP_MAINTAINED, AMOUNT_ELECTRICITY, AMOUNT_NONENERGY, AMOUNT_DIESEL, AMOUNT_MANAGED, AMOUNT_MAINTAINED, SITE_SPECIFIC_PRICING, AMENDMENT_ITEM, PCT_OF_NON_ENERGY_LEASE_RATE, CURRENCY, BENCHMARK_INDEX_OF_ESC, AMENDMENT_AMOUNT, FIRST_MONTH_ESC_APPLICABLE, FREQUENCY_OF_ESCALATION, ESCALATION_CAP_PCT, ESCALATION_FLOOR_PCT, ESCALATION_MULTIPLIER_PCT, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, START_DATE, CANCELLATION_DATE, QUANTITY, LEASE_RATE_TYPE, CUSTOMER_REGION, LEASE_RATE_COMPONENT, SAP_INVOICE_RESPONSE_ID, SAP_INVOICE_RESPONSE_CODE, SAP_INVOICE_RESPONSE_DESC, CURR_STAGE, ERROR_CODE, ERROR_DESCRIPTION, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, CHARGE_FIELD1, CHARGE_FIELD2, CHARGE_FIELD3, CHARGE_FIELD4, CHARGE_FIELD5, CHARGE_FIELD6, CHARGE_FIELD7, CHARGE_FIELD8, CHARGE_FIELD9, CHARGE_FIELD10, CHARGE_FIELD11, CHARGE_FIELD12, CHARGE_FIELD13, CHARGE_FIELD14, CHARGE_FIELD15, CHARGE_FIELD16, CHARGE_FIELD17, CHARGE_FIELD18, CHARGE_FIELD19, CHARGE_FIELD20, CHARGE_FIELD21, CHARGE_FIELD22, CHARGE_FIELD23, CHARGE_FIELD24, CHARGE_FIELD25, CHARGE_FIELD26, CHARGE_FIELD27, CHARGE_FIELD28, CHARGE_FIELD29, CHARGE_FIELD30, CHARGE_FIELD31, CHARGE_FIELD32, CHARGE_FIELD33, CHARGE_FIELD34, CHARGE_FIELD35, CHARGE_FIELD36, CHARGE_FIELD37, CHARGE_FIELD38, CHARGE_FIELD39, CHARGE_FIELD40, CHARGE_FIELD41, CHARGE_FIELD42, CHARGE_FIELD43, CHARGE_FIELD44, CHARGE_FIELD45, CHARGE_FIELD46, CHARGE_FIELD47, CHARGE_FIELD48, CHARGE_FIELD49, CHARGE_FIELD50, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7, FIELD8, FIELD9, FIELD10, FIELD11, FIELD12, FIELD13, FIELD14, FIELD15, FIELD16, FIELD17, FIELD18, FIELD19, FIELD20, FIELD21, FIELD22, FIELD23, FIELD24, FIELD25, FIELD26, FIELD27, FIELD28, FIELD29, FIELD30, FIELD31, FIELD32, FIELD33, FIELD34, FIELD35, FIELD36, FIELD37, FIELD38, FIELD39, FIELD40, FIELD41, FIELD42, FIELD43, FIELD44, FIELD45, FIELD46, FIELD47, FIELD48, FIELD49, FIELD50, FIELD51, FIELD52, FIELD53, FIELD54, FIELD55, FIELD56, FIELD57, FIELD58, FIELD59, FIELD60, FIELD61, FIELD62, FIELD63, FIELD64, FIELD65, FIELD66, FIELD67, FIELD68, FIELD69, FIELD70, FIELD71, FIELD72, FIELD73, FIELD74, FIELD75, FIELD76, FIELD77, FIELD78, FIELD79, FIELD80, FIELD81, FIELD82, FIELD83, FIELD84, FIELD85, FIELD86, FIELD87, FIELD88, FIELD89, FIELD90, FIELD91, FIELD92, FIELD93, FIELD94, FIELD95, FIELD96, FIELD97, FIELD98, FIELD99, FIELD100, FIELD101, FIELD102, FIELD103, FIELD104, FIELD105, FIELD106, FIELD107, FIELD108, FIELD109, FIELD110, FIELD111, FIELD112, FIELD114, FIELD115, FIELD116, FIELD117, FIELD118, FIELD119, FIELD120, FIELD121, FIELD122, FIELD123, FIELD124, FIELD125, FIELD126, FIELD127, FIELD128, FIELD129, FIELD130, FIELD131, FIELD132, FIELD133, FIELD134, FIELD135, FIELD136, FIELD137, FIELD138, FIELD139, FIELD140, FIELD141, FIELD142, FIELD143, FIELD144, FIELD145, FIELD146, FIELD147, FIELD148, FIELD149, FIELD150,CUSTOMER_ID, NE_ESCALATED_BASE_PRICE, NE_ON_AIR_EFFECTIVE_PRICE, NE_ON_AIR_EFFECTIVE_PRICE_LC, TOTAL_NE_PRICE, ENERGY_BASE_PRICE_DG, ENERGY_BASE_PRICE_EB, ENERGY_CE_DG, ENERGY_CE_EB, ENERGY_ESCALATED_BASE_PRICE_DG, ENERGY_ESCALATED_BASE_PRICE_EB, ENERGY_ON_AIR_EFF_PRICE_DG, ENERGY_ON_AIR_EFF_PRICE_EB, TOTAL_ENERGY_ON_AIR_EFF_PRICE, ENERGY_ON_AIR_EFF_PRICE_LC, ENERGY_AMENDMENT_PRICE, TOTAL_ENERGY_PRICE, ADDITIONAL_RATE, SITE_COUNT, NE_BASE_PRICE, NE_CUMULATIVE_ESCALATION, NE_AMENDMENT_PRICE, LEGACY_AMOUNT, LEGACY_FEE, LEGACY_AMOUNT_CURRENCY, AMENDMENT_CURRENCY, AMENDMENT_QTY_SUM, BILLING_TRANSACTION_STATUS, L1_REMARKS, L2_REMARKS, CUSTOMER_REMARKS, L3_REMARKS, L4_REMARKS, L5_REMARKS, INVOICE_STATUS, BACK_BILL_DATE, BACK_BILL_MONTH, LAST_YEAR_ELECTRICITY_PRICE, LAST_YEAR_DIESEL_PRICE, SITE_SPECIFIC_PRICING_STR, CPI_ESC_NON_ENERGY, CPI_ESC_DG, CPI_ESC_EB, INVOICE_CREATION_DATE, LEGACY_FEE_AMOUNT, LEGACY_FEE_AMOUNT_ESC, LEGACY_FEES, UUID, CURRENCY_DG, CURRENCY_EB, CURRENCY_NE, SITE_DETAILS_MONTH, TENANCY_DETAILS_MONTH, LEASE_DETAILS_MONTH, AMD_QTY_DETAILS_MONTH, AMD_PRC_DETAILS_MONTH, AMOUNT_NONENERGY_CONFIG, AMOUNT_NONENERGY_NON_USD, AMOUNT_NONENERGY_LC, AMOUNT_NONENERGY_USD, AMOUNT_NONENERGY_GROUND, AIRTEL_OUTDOOR, NO_OF_SITES_THRESHHOLD, LEASE_EXPIRY_DATE, VOLUME_COMMITMENT, DIESEL_BASE_PRICE, ELECTRICITY_BASE_PRICE, DIESEL_ESCALATION, ELECTRICITY_ESCALATION, DIESEL_ESCALATED_AMOUNT, ELECTRICITY_ESCALATED_AMOUNT, TENANCY_DISCOUNT_DIESEL, TENANCY_DISCOUNT_ELECTRICITY, ADJUSTED_DIESEL_AMOUNT, ADJUSTED_ELECTRICITY_AMOUNT, ON_AIR_EFFECTIVE_DIESEL_AMOUNT, ON_AIR_EFFECTIVE_ELECTRICITY_AMOUNT, TOTAL_ENERGY_AMOUNT_MW, DIESEL_BASE_AMOUNT_ON_GRID, ELECTRICITY_BASE_AMOUNT_ON_GRID, DIESEL_BASE_PRICE_OFF_GRID, NE_BASE_USD_NON_ESCALATOR, SECTOR_OPERATIONAL, CONFIGURATION_ADDITIONAL, GROUND_RENT, LC_ESCALATOR_CE, USD_ESCALATOR_CE, USD_NON_ESCALATOR_CE, CONFIGURATION_ADDITIONAL_CE, LC_ESC_ESCALATED_AMOUNT, USD_ESC_ESCALATED_AMOUNT, USD_NON_ESC_ESCALATED_AMOUNT, CONFIG_ADDITIONAL_ESCALATED, CATEGORY_SLA_SERVICE, VOLUME_DISCOUNT, SITE_TYPE_DISCOUNT, TENANCY_DISCOUNT_NON_ENERGY, SITE_UPTIME_CATEGORY_DISCOUNT, CONVERTED_TO_OUTDOOR_DISCOUNT, TOTAL_MENU_PRICING, TOTAL_PRICING_ADJUSTMENT, LC_ESCALATOR_MONTHLY, USD_ESCALATOR_MONTHLY, USD_NON_ESCALATOR_MONTHLY, TOTAL_ON_AIR_EFFECTIVE_PRICE, NE_BASE_LC_ESCALATOR, NE_BASE_USD_ESCALATOR, ON_AIR_EFF_ELECTRICITY_AMOUNT, ON_AIR_EFF_DIESEL_AMOUNT, SLA_SERVICE_CREDIT_REWARD, MENU_PRICING_ENERGY, OUTDOOR_DISCOUNT, DATE_KPI, AMOUNT_MW, TENANCY_VOLUME_DISCOUNT, SAP_POSTING_STATUS, SAP_POSTING_DATE, AMD_BASE, RECONCILED_AMOUNT, TOTAL_ON_AIR_EFFECTIVE_PRICE_VAR, TOTAL_ENERGY_AMOUNT_MW_VAR, CALCULATED_DOWNTIME_SITE_WISE, SLA_CREDIT, RECONCILED_AMOUNT_VT, SITE_CLASS_TYPE, ADDITIONAL_RATE_AIRTEL, TOTAL_NE_PRICE_USD, NE_AMENDMENT_PRICE_AIRTEL, RECONCILED_AMOUNT_AIRTEL, ID, LEGACY_SITE_DISCOUNT, SITE_SPECIFIC_DISCOUNT, AMOUNT_EVS_USD_ESC, CPI_EVS_USD_ESC, CPI_EVS_ENERGY_DG, AMENDMENT_ONLY_DISCOUNT, BILLING_TYPE_CHANGE_EFFECTIVE_DATE, STRATEGIC_SITE_PREMIUM, ADJUSTED_DIESEL_DELIVERY_AMT, ON_AIR_EFF_DIESEL_DELIVERY_AMT, DIESEL_DELIVERY_ESCALATED_AMT, DIESEL_DELIVERY_ESCALATION, DIESEL_DELIVERY_BASE_PRICE, NE_ON_AIR_FULL_MONTH_PRICE, ENERGY_ONAIR_FULL_MONTH_EB, ENERGY_ONAIR_FULL_MONTH_DG, NE_USD_ESC_ESC_AMT_EVS, NE_USD_ESC_CE_EVS, NE_USD_ESC_BASE_EVS, ENERGY_DG_BASE_EVS, ENERGY_CE_EVS, ADD_ENERGY_DG_ESC_AMT_EVS, CPI_ESC_DG_DELIVERY, AMOUNT_EVS_ENERGY_DG, AMOUNT_DIESEL_DELIVERY, LEGACY_DISCOUNT, AMOUNT_EVS_EB, CPI_EVS_EB, CPI_EVS_EB_NEXT, ACTION_PERMITTED_EVS_EB, ENERGY_EB_BASE_EVS, ENERGY_EB_CE_EVS, ADD_ENERGY_EB_ESC_AMT_EVS, USD_BASE_NONESCALATOR_MONTHLY, USD_BASE_ESCALATOR_MONTHLY, LC_BASE_ESCALATOR_MONTHLY, USD_NON_ESCALATED_AMOUNT, USD_ESCALATED_AMOUNT, LC_ESCALATED_AMOUNT, USD_BASE_NON_ESCALATOR, USD_BASE_ESCALATOR, LC_BASE_ESCALATOR, NE_USD_BASE_ESCALATOR, NE_LC_BASE_ESCALATOR, NE_USD_BASE_NON_ESCALATOR, AMOUNT_SECTOR_OPERATIONAL_CHARGE, AMOUNT_STANDARD_CONFIGURATION_PREMIUM, AMOUNT_DIFFICULT_SITE_PREMIUM, AMOUNT_LC_ESCALATING_DEC_23_AMEND, AMOUNT_LC_ESCALATING_BASE, AMOUNT_USD_ESCALATING_BASE, AMOUNT_USD_NON_ESCALATING_BASE, AMOUNT_USD_ESCALATING_DEC_23_AMEND, AMOUNT_USD_NON_ESCALATING_DEC_23_AMEND, CPI_RATE_SECTOR_OPERATIONAL_CHARGE, CPI_RATE_STANDARD_CONFIGURATION_PREMIUM, CPI_RATE_DIFFICULT_SITE_PREMIUM, CPI_RATE_LC_ESCALATING_DEC_23_AMEND, CPI_RATE_LC_ESCALATING_BASE, CPI_RATE_USD_ESCALATING_BASE, CPI_RATE_USD_NON_ESCALATING_BASE, CPI_RATE_USD_ESCALATING_DEC_23_AMEND, CPI_RATE_USD_NON_ESCALATING_DEC_23_AMEND, CPI_USD_LC_ESC, CPI_USD_ESC, CPI_USD_NON_ESC, TOTAL_ON_AIR_EFF_PRICE, PRORATION, ADDITIONAL_RATE_ADVANCE, CPI_USD_CONFIG, CPI_RATE_DG, CPI_RATE_EB, CPI_RATE_NON_ENERGY, STARTING_NO_OF_DAYS, TOTAL_NO_OF_DAYS, END_NUMBER_OF_DAYS, TOTAL_ENERGY_AMOUNT_MW_ADVANCE, ACTION_PERMITTED, DG_ACTION_PERMITTED, EB_ACTION_PERMITTED, ACTION_PERMITTED_USD_ESC, ACTION_PERMITTED_ENERGY_DEISEL, CPI_EVS_USD_ESC_NEXT, CPI_EVS_ENERGY_DG_NEXT, CPI_RATE_GROUND_RENT_CHARGE, AMOUNT_CAPEX_RECOVERY, CPI_CAPEX_RECOVERY, CURRENCY_CAPEX_RECOVERY, ADDITIONAL_UNIT_CONSUMED, AMOUNT_PER_UNIT, ADDITIONAL_POWER_USAGE, ENERGY_ADDITIONAL_PRICE_EB, ENERGY_ADD_ESCALATED_EB, DIFFICULT_SITE_PREMIUM_APPLICABLE, STANDARD_CONFIGURATION_PREMIUM, DIFFICULT_SITE_PREMIUM_MGA, NE_LC_ESCALATOR_DEC_23_ADD, NE_USD_ESCALATOR_DEC_23_ADD, NE_USDNON_ESCALATOR_DEC_23_ADD, NE_USDNON_ESCAL_DEC_23_ADD_CE, NE_USD_ESCALATOR_DEC_23_ADD_CE, NE_LC_ESCALATOR_DEC_23_ADD_CE, STANDARD_CONFIG_PREMIUM_CE, DIFFICULT_SITE_PREMIUM_CE, SECTOR_OPERATIONAL_CE, GROUND_RENT_CE, STD_CONFIG_PREMIUM_ESCALATED, DIFFIC_SITE_PREMIUM_ESCALATED, NE_LC_DEC_23_ADD_ESCALATED_AMT, NE_USD_DEC_23_ADD_ESCALATED, NE_USDNON_DEC_23_ADD_ESCALATED, SECTOR_OPERATIONAL_ESCALATED, GROUND_RENT_ESCALATED_MGA, NE_LC_DEC_23_ADD_MONTHLY, DIFFICULT_SITE_PREMIUM_MONTHLY, STD_CONFIG_PREMIUM_MONTHLY, NE_USD_DEC_23_ADD_MONTHLY, NE_USD_NON_DEC_23_ADD_MONTHLY, GROUND_RENT_MONTHLY_MGA, SECTOR_OPERATIONAL_MONTHLY_MGA, DEACTIVATION_LEASE_RATE, ITP_APPLICABLE, DEPOSIT_AMOUNT, FX_RATE1, CURRENCY_USD_ESCALATING, CURRENCY_LC_NON_ESCALATING, CURRENCY_USD_NON_ESCALATING, CURRENCY_LC_ESCALATING, CURRENCY_GROUND_RENT_CHARGE, CURRENCY_CONFIGURATION_ADDITIONAL_CHARGE, CURRENCY_EUR_ESCALATING, CURRENCY_NON_ESCALATION, CURRENCY_XAF_ESCALATING, CURRENCY_NO_ESCALATION, CURRENCY_SECTOR_OPERATIONAL_CHARGE, CURRENCY_STANDARD_CONFIGURATION_PREMIUM, CURRENCY_DIFFICULT_SITE_PREMIUM, CURRENCY_LC_ESCALATING_DEC_23_AMEND, CURRENCY_LC_ESCALATING_BASE, CURRENCY_USD_ESCALATING_BASE, CURRENCY_USD_NON_ESCALATING_BASE, CURRENCY_USD_ESCALATING_DEC_23_AMEND, CURRENCY_USD_NON_ESCALATING_DEC_23_AMEND, ENERGY_BASE_PRICE_SNFR_CPI_ESC, ENERGY_ESC_EB_SNFR_CPI_ESC, ENERGY_CE_EB_SNFR_CPI_ESC, AMOUNT_CPI_ESCALATING, CPI_RATE_CPI_ESCALATING, CURRENCY_CPI_ESCALATING, TAX_AMOUNT, TAX_CODE, NET_AMOUNT, TAX_PERCENTAGE, BILLING_PARAMETER, INVOICE_CREATION_DATE_TIME, INVOICE_APPROVED_DATE, CUSTOMER_SHARED_DATE, BOOKED_IN_SAP_DATE, PROJECT_NAME, ITP_REFERENCE, SAP_ERROR, SAP_ERR_TEST, UNIQUE_REF)

        TXN_SITE_DETAILS(COUNTRY_ID, COUNTRY_NAME, BILL_MONTH, SEARCH_MONTH, ST_ID, SITERRA_SITE_ID, SITE_NAME, SITE_TYPE, INTERNAL_SLA_CLASS, LEGACY_ID, FINANCE_ID, OWNERSHIP_TYPE, GRID_STATUS, SHARABILITY, REGION_NAME, PROVINCE, PORTFOLIO, SITE_STATUS, SITE_SOURCE, GRID_CONNECTION_DATE, ANCHOR_TENANT, MULTI_TENANCY_STATUS, TENANTS_TOTAL, ON_AIR_DATE, CONSOL_DATE, DECOM_DATE, OFFLINE_DATE, RELO_DATE, TENANT_LOAD_POSITION1, TENANT_LOAD_POSITION2, TENANT_LOAD_POSITION3, TENANT_LOAD_POSITION4, TRANSACTION_STATUS, STATUS, ERROR_CODE, ERROR_DESCRIPTION, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, CURR_STAGE, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7, FIELD8, FIELD9, FIELD10, FIELD11, FIELD12, FIELD13, FIELD14, FIELD15, FIELD16, FIELD17, FIELD18, FIELD19, FIELD20, FIELD21, FIELD22, FIELD23, FIELD24, FIELD25, FIELD101, FIELD102, FIELD103, FIELD104, FIELD105, FIELD106, FIELD107, FIELD108, FIELD109, FIELD110, ID
    )
        TXN_TENANCY_DETAILS(COUNTRY_ID, BILL_MONTH, SEARCH_MONTH, SITERRA_TENANCY_ID, SITERRA_SITE_ID, SAP_CUSTOMER_NO, CUSTOMER_SITE_ID, CUSTOMER_NAME_KNOWN_AS, LEASESTATUS, TENANCY_TYPE, OUTDOOR, MASTER_CLASSIFICATION, TENANCY_CLASSIFICATION_SITE_BILLING_TYPE, SITE_CLASS, MOVE_IN_DATE, MOVE_OUT_DATE, SLA_START_DATE, RFI_DATE, SAF_DATE, ORIGINAL_EXPIRATION_DATE, CLASSIFICATION_OVER_RIDE, CANCEL_DATE, REPORTING_DATE, LEASESTART_DATE, RENT_FREE_PERIOD, RENT_START_DATE, SLA_CLASS, TRANSACTION_STATUS, STATUS, ERROR_CODE, ERROR_DESCRIPTION, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, CURR_STAGE, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7, FIELD8, FIELD9, FIELD10, FIELD11, FIELD12, FIELD13, FIELD14, FIELD15, FIELD16, FIELD17, FIELD18, FIELD19, FIELD20, FIELD21, FIELD22, FIELD23, FIELD24, FIELD25, FIELD101, FIELD102, FIELD103, FIELD104, FIELD105, FIELD106, FIELD107, FIELD108, FIELD109, FIELD110, CUSTOMER_ID, LEASE_EXPIRY_DATE, VOLUME_COMMITMENT, VOLUME_DISCOUNT, TENANCY_VOLUME_DISCOUNT, SITE_CLASS_TYPE, ID, BILLING_TYPE_CHANGE_EFFECTIVE_DATE, AMENDMENT_ONLY_DISCOUNT, SITE_SPECIFIC_DISCOUNT, DIFFICULT_SITE_PREMIUM_APPLICABLE
    )
        TXN_BASE_LEASE_RATE(COUNTRY_ID, BILL_MONTH, SEARCH_MONTH, SITERRA_SITE_ID, SAP_CUSTOMER_NO, CUSTOMER_REGION, TENANCY_CLASSIFICATION_SITE_BILLING_TYPE, AIRTEL_SPECIAL_OFFER, SITE_CLASS, CURRENCY, LEASE_RATE_TYPE, LEASE_COMPONENT, LEASE_AMOUNT, TRANSACTION_STATUS, STATUS, ERROR_CODE, ERROR_DESCRIPTION, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, CURR_STAGE, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7, FIELD8, FIELD9, FIELD10, FIELD11, FIELD12, FIELD13, FIELD14, FIELD15, FIELD16, FIELD17, FIELD18, FIELD19, FIELD20, FIELD21, FIELD22, FIELD23, FIELD24, FIELD25, FIELD101, FIELD102, FIELD103, FIELD104, FIELD105, FIELD106, FIELD107, FIELD108, FIELD109, FIELD110, GRID_STATUS, ID, CUSTOMER_ID
    )
        TXN_AMD_QUANTITY(COUNTRY_ID, BILL_MONTH, SEARCH_MONTH, SITERRA_SITE_ID, SAP_CUSTOMER_NO, START_DATE, CANCELLATION_DATE, AMD_QUANTITY_ITEM, QUANTITY, GRID_STATUS, TRANSACTION_STATUS, STATUS, ERROR_CODE, ERROR_DESCRIPTION, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, CURR_STAGE, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7, FIELD8, FIELD9, FIELD10, FIELD11, FIELD12, FIELD13, FIELD14, FIELD15, FIELD16, FIELD17, FIELD18, FIELD19, FIELD20, FIELD21, FIELD22, FIELD23, FIELD24, FIELD25, FIELD101, FIELD102, FIELD103, FIELD104, FIELD105, FIELD106, FIELD107, FIELD108, FIELD109, FIELD110, ID, CUSTOMER_ID, PROJECT_NAME, ITP_REFERENCE, UNIQUE_REF
    )
        TXN_AMD_PRICING(COUNTRY_ID, BILL_MONTH, SEARCH_MONTH, SITERRA_SITE_ID, SAP_CUSTOMER_NO, SITE_SPECIFIC_PRICING, AMD_PRICING_ITEM, PCT_OF_NON_ENERGY_LEASE_RATE, CURRENCY, BENCHMARK_INDEX_OF_ESC, AMD_AMOUNT, FIRST_MONTH_ESC_APPLICABLE, FREQUENCY_OF_ESCALATION, ESCALATION_CAP_PCT, ESCALATION_FLOOR_PCT, ESCALATION_MULTIPLIER_PCT, EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, TRANSACTION_STATUS, STATUS, ERROR_CODE, ERROR_DESCRIPTION, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, CURR_STAGE, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7, FIELD8, FIELD9, FIELD10, FIELD11, FIELD12, FIELD13, FIELD14, FIELD15, FIELD16, FIELD17, FIELD18, FIELD19, FIELD20, FIELD21, FIELD22, FIELD23, FIELD24, FIELD25, FIELD101, FIELD102, FIELD103, FIELD104, FIELD105, FIELD106, FIELD107, FIELD108, FIELD109, FIELD110, SITE_SPECIFIC_PRICING_STR, ID, GRID_STATUS, CUSTOMER_ID
    )

        {user_query}
        """
        response = model.generate_content(sql_prompt)
        logging.info(f"Generated SQL: {response.text.strip()}")
        sql_raw = response.text.strip()
        if sql_raw.startswith("```"):
            sql_raw = sql_raw.split("```")[1]
            sql_raw = sql_raw.replace("sql", "").strip()
        return sql_raw.rstrip(";").strip()
    except Exception as e:
        logging.error(f"Error in generate_sql: {str(e)}", exc_info=True)
        raise
 
def generate_explanation(df):
    """Generate business explanation of dataframe"""
    result_summary = df.head().to_string(index=False)
    explain_prompt = f"""
    You are a business analyst. Provide a simple, direct natural language summary of the SQL result without mentioning SQL code.
    Just give the business insight from the result. Example: "There are 10 invoices present in the database."
 
    Result:
    {result_summary}
    """
    response = model.generate_content(explain_prompt)
    return response.text.strip()

def classify_intent(text):
    """
    Classify user input as 'greeting', 'query', or 'other' using Gemini LLM.
    """
    logging.info(f"Classifying intent for text: {text}")
    try:
        prompt = (
            "Classify the following user input as either 'greeting', 'query', or 'other'. "
            "Only reply with one of these words: 'greeting', 'query', or 'other'.\n"
            f"User input: {text}"
        )
        response = model.generate_content(prompt)
        intent = response.text.strip().lower()
        logging.info(f"Classified intent: {intent}")
        return intent
    except Exception as e:
        logging.error(f"Error in classify_intent: {str(e)}", exc_info=True)
        raise

def generate_greeting_reply(text):
    """Generate a natural language reply to a greeting using Gemini LLM."""
    logging.info(f"Generating greeting reply for: {text}")
    try:
        prompt = (
            "The user sent the following greeting or small talk. "
            "Reply in a friendly, conversational way as a helpful assistant.\n"
            f"User: {text}\n"
            "Assistant:"
        )
        response = model.generate_content(prompt)
        reply = response.text.strip()
        logging.info(f"Generated greeting reply: {reply}")
        return reply
    except Exception as e:
        logging.error(f"Error in generate_greeting_reply: {str(e)}", exc_info=True)
        raise